#on:
#  schedule:
#    - cron: '0 0 * * *'  # Runs every day at midnight UTC

name: Run PowerShell script on branch create
on:
  create:
    branches:
      - '*'

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Fetch events from Sessionize.com API
        run: |
          $branchName = "${{ github.ref }}"
          $branchName = $branchName -replace 'refs/heads/', ''
          $response = Invoke-RestMethod -Uri 'https://sessionize.com/api/v2/7tsmuj82/view/Sessions'
          Write-Output $response
          $events = $response | ConvertTo-Json
          $date = Get-Date -Format 'yyyy-MM-dd'
          $year = Get-Date -Format 'yyyy'
          $month = Get-Date -Format 'MM'
          $branchName = "events/$date"
          $filePath = "meetings/$year/$month/$date.json"
          New-Item -Path $filePath -Force -Value $events
          
      - name: Run PowerShell script
        run: |
          $branchName = "${{ github.ref }}"
          $branchName = $branchName -replace 'refs/heads/', ''
          Write-Output $BranchName
          .\script.ps1 -BranchName $branchName
          
